#docker compose -f docker-compose-spring-gateway.yml up -d

version: '3.3'
services:
  dbserver:
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: distribuida
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "c:/db-distribuida:/var/lib/postgresql/data"
    ports:
      - "54321:5432"
    expose:
      - 5432
  consul:
    image: consul:1.15.4
    command: |
      agent -dev
      -ui
      -bind 0.0.0.0
      -client 0.0.0.0
    ports:
      - "8500:8500"
    expose:
      - 8500
  proxy:
    image: traefik:v3.3.1
    command: |
      --api.insecure=true
      --providers.consulCatalog
      --providers.consulCatalog.exposedByDefault=false
      --providers.consulCatalog.refreshInterval=5s
      --providers.consulCatalog.endpoint.address=consul:8500
      --providers.docker
      --providers.docker.exposedByDefault=false
      --entryPoints.metrics.address=":8082"
      --entryPoints.http.address=":80"
      --metrics.prometheus.entryPoint=metrics
      --tracing=true
      --tracing.addinternals=false
      --tracing.otlp=true
      --tracing.otlp.http=true
      --tracing.otlp.http.endpoint=http://jaeger:4318
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "8080:8080"
      - "8082:8082"
      - "80:80"
    expose:
      - 80
    depends_on:
      - consul
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs:/etc/prometheus
    ports:
      - "9090:9090"
    expose:
      - 9090
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    expose:
      - 3000
  jaeger:
    image: jaegertracing/jaeger:2.2.0
    ports:
      - "16686:16686" #UI
      - "4317:4317"   #gRTC
      - "4318:4318"   #HTTP
    expose:
      - 16686
      - 4317
      - 4318
    depends_on:
      - proxy
  authors:
    image: aaguamaninga/app-authors-spring:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-authors.rule=PathPrefix(`/app-authors`)"
      - "traefik.http.routers.app-authors.middlewares=mauthors"
      - "traefik.http.middlewares.mauthors.stripPrefix.prefixes=/app-authors"
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      SPRING_HTTP_PORT: 8080
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    expose:
      - 8080
    depends_on:
      - dbserver
      - consul
    deploy:
      replicas: 3
  books:
    image: aaguamaninga/app-books-spring:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-books.rule=PathPrefix(`/app-books`)"
      - "traefik.http.routers.app-books.middlewares=mbooks"
      - "traefik.http.middlewares.mbooks.stripPrefix.prefixes=/app-books"
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      SPRING_HTTP_PORT: 8080
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    expose:
      - 8080
    depends_on:
      - dbserver
      - consul
      - authors
    deploy:
      replicas: 1

